DROP TABLE IF EXISTS article;
DROP TABLE IF EXISTS member;

CREATE TABLE IF NOT EXISTS member (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE,
    age INTEGER
);

CREATE TABLE IF NOT EXISTS article (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(256),
   description VARCHAR(4096),
   created DATETIME,
   updated DATETIME,
   author INTEGER,
   FOREIGN KEY(author) REFERENCES member(id) ON DELETE CASCADE
);

