--DROP TABLE IF EXISTS member CASCADE;
--DROP TABLE IF EXISTS article CASCADE;

CREATE TABLE member (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE,
    age INTEGER
);

CREATE TABLE article (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(256),
   description VARCHAR(4096),
   created DATETIME,
   updated DATETIME,
   member_id INTEGER,
   FOREIGN KEY(member_id) REFERENCES member(id) ON DELETE CASCADE
);
